# Bases and transformations
The following tasks are designed to provide a refresher on bases and transformations between them.

<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#basis">Task 1: Identifying Basis Vectors</a>
            </li>
            <li>
            <a href="#basis_combined">Task 2: Basis Transformation and Change of Coord…</a>
            </li>
            <li>
            <a href="#basis4">Task 3: Applying a Linear Transformation in Diff…</a>
            </li>
            <li>
            <a href="#basis5">Task 4: Basis and Dimensionality Check</a>
            </li>
        </ul>
    </div>
</article>

<article class="message task"><a class="anchor" id="basis"></a>
    <div class="message-header">
        <span>Task 1: Identifying Basis Vectors</span>
        <span class="has-text-right">
          <i class="bi bi-infinity"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Given the following bases vectors for $\mathbb{R}^2$:

$$
\begin{array}{l}
1. \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\} \\[12pt]
2. \left\{ \begin{bmatrix} 2 \\ 3 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\} \\[12pt]
3. \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 2 \\ 2 \end{bmatrix} \right\} \\
\end{array}
$$
1. Which of these sets forms a basis for $\mathbb{R}^2 $? Justify your answer by checking linear independence and spanning the vector space.



</div></article>



In [0]:
# As any vector in R^2 can be defined using the two vectors in 1 those are basis vectors
# Thus: [x, y] = x[1, 0] + y[0, 1]

<article class="message task"><a class="anchor" id="basis_combined"></a>
    <div class="message-header">
        <span>Task 2: Basis Transformation and Change of Coordinates</span>
        <span class="has-text-right">
          <i class="bi bi-infinity"></i><i class="bi bi-stoplights hard"></i>
        </span>
    </div>
<div class="message-body">


Consider three bases in  $\mathbb{R}^2$:
1. The standard basis  
$$E = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\}$$
 
2. The basis  
$$B   = \left\{ \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \begin{bmatrix} 2 \\ -1 \end{bmatrix} \right\}$$
 
3. The basis  
$$C   = \left\{ \begin{bmatrix} 2 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ 3 \end{bmatrix} \right\}$$
 

Given two vectors in the standard basis:

$$
\text{v} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, 
\text{w} = \begin{bmatrix} 7 \\ 6 \end{bmatrix} 
$$
1. Draw the basis vectors for  $E$,  $B$ , and  $C$ and the vectors $\text{v}$ and $\text{w}$  on a piece of paper.

2. Express $\text{v}$ and $\text{w}$  in the basis  $B$. 

3. Express $\text{v}$  and $\text{w}$  in the basis $C$.

4. Find the change of basis matrix  $T_E^B$ that given a vector expressed in the basis  E  maps it to the basis B. 

5. Find the change of basis matrix  $T_E^C$ that given a vector expressed in the basis  E  maps it to the basis C.

6. Use the change of basis matrices to transform  $\text{v}$ and $\text{w}$ from standard basis to the basis $B$ and $C$ respectively. Verify that the resulting coordinates match your results from the previous steps.




</div></article>



In [3]:
import numpy as np
# v, w = 4.8*B1 + 2.625*B2
# v, w = 4.625*C1 + 0.83*C2
E = np.array([[1,0],[0,1]])
B = np.array([[1,2],[2,-1]])
C = np.array([[2,1],[1,3]])
v = np.array([3,1])
w = np.array([7,6])

v_B = np.linalg.solve(B.T, v)
w_B = np.linalg.solve(B.T, w)

v_C = np.linalg.solve(C.T, v)
w_C = np.linalg.solve(C.T, w)

print(f"v in Basis B: {v_B} - w in Basis B: {w_B}")
print(f"v in Basis C: {v_C} - w in Basis C: {w_C}")

T_B_E = B.T
T_C_E = C.T

print(f"T^B_E (Standard to Basis B): \n{T_B_E}")
print(f"T^C_E (Standard to Basis C): \n{T_C_E}")

v in Basis B: [1. 1.] - w in Basis B: [3.8 1.6]
v in Basis C: [ 1.6 -0.2] - w in Basis C: [3. 1.]
T^B_E (Standard to Basis B): 
[[ 1  2]
 [ 2 -1]]
T^C_E (Standard to Basis C): 
[[2 1]
 [1 3]]


<article class="message task"><a class="anchor" id="basis4"></a>
    <div class="message-header">
        <span>Task 3: Applying a Linear Transformation in Different Bases</span>
        <span class="has-text-right">
          <i class="bi bi-infinity"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Let $ T: \mathbb{R}^2 \to \mathbb{R}^2 $ be a linear transformation represented by the matrix:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

in the standard basis. Let 

$$
B = \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\}
$$
 
be a new basis.
1. Calculate the matrix that represents $ T $ with respect to the basis $ B $. Use the change of basis matrices to show your work.



</div></article>



In [5]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[-1,2]])
T_B_E = np.column_stack((B[:,0], B[:,1]))
T_E_B = np.linalg.inv(T_B_E)
A_B = T_E_B @ A @ T_B_E

print("Matrix A (Standard Basis):\n", A)
print("\nChange of Basis Matrix (T_B^E):\n", T_B_E)
print("\nInverse Change of Basis Matrix (T_E^B):\n", T_E_B)
print("\nMatrix A in Basis B (A_B):\n", A_B)

Matrix A (Standard Basis):
 [[1 2]
 [3 4]]

Change of Basis Matrix (T_B^E):
 [[ 1  1]
 [-1  2]]

Inverse Change of Basis Matrix (T_E^B):
 [[ 0.66666667 -0.33333333]
 [ 0.33333333  0.33333333]]

Matrix A in Basis B (A_B):
 [[-0.33333333 -0.33333333]
 [-0.66666667  5.33333333]]


<article class="message task"><a class="anchor" id="basis5"></a>
    <div class="message-header">
        <span>Task 4: Basis and Dimensionality Check</span>
        <span class="has-text-right">
          <i class="bi bi-infinity"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Suppose $ \mathbb{R}^3 $ has a basis given by 

$$
B = \left\{ \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ -1 \\ 0 \end{bmatrix} \right\}.
$$

1. Verify that $ B $ is a basis by showing it spans $ \mathbb{R}^3 $ and is linearly independent.
2. If a fourth vector $ \begin{bmatrix} 2 \\ -1 \\ 3 \end{bmatrix} $ is added to $ B $, does it still form a basis for $ \mathbb{R}^3 $? Explain your reasoning in terms of dimension.



</div></article>



In [ ]:
# Below seems to be incorrect. I cannot figure it out.

# --- 1) Define the three vectors that purportedly form a basis for R^3 ---
v1 = np.array([1,  0,  1])
v2 = np.array([0,  1,  1])
v3 = np.array([1, -1,  0])

# Create a matrix B whose columns are v1, v2, v3
B = np.column_stack((v1, v2, v3))
print("Matrix B:\n", B)

# Check linear independence by computing the rank (or determinant)
rank_B = np.linalg.matrix_rank(B)
det_B = np.linalg.det(B)
print("\nRank of B =", rank_B)
print("Determinant of B =", det_B)

if rank_B == 3:
    print("=> The vectors are linearly independent and span R^3, so they form a basis.")
else:
    print("=> The vectors do NOT form a basis for R^3.")

# --- 2) Add a fourth vector and check what happens ---
v4 = np.array([2, -1,  3])
B4 = np.column_stack((B, v4))
print("\nMatrix B4 (with the fourth vector):\n", B4)

rank_B4 = np.linalg.matrix_rank(B4)
print("\nRank of B4 =", rank_B4)

if rank_B4 == 4:
    print("=> These 4 vectors would form a basis for R^4 (if we were in R^4).")
else:
    print("=> In R^3, adding a 4th vector must make them linearly dependent, so this is not a basis for R^3.")


Matrix B:
 [[ 1  0  1]
 [ 0  1 -1]
 [ 1  1  0]]

Rank of B = 2
Determinant of B = 0.0
=> The vectors do NOT form a basis for R^3.

Matrix B4 (with the fourth vector):
 [[ 1  0  1  2]
 [ 0  1 -1 -1]
 [ 1  1  0  3]]

Rank of B4 = 3
=> In R^3, adding a 4th vector must make them linearly dependent, so this is not a basis for R^3.
