In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


In [2]:
A - B

array([[ 17.        , -14.5       ,  14.33333333, -12.75      ],
       [ 12.5       , -10.66666667,  10.25      ,  -8.8       ],
       [  8.33333333,  -6.75      ,   6.2       ,  -4.83333333],
       [  4.25      ,  -2.8       ,   2.16666667,  -0.85714286]])

In [11]:
print(np.dot(A, C))
print(np.dot(C, A))

[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]


Different since A dot B means we for [i][j] calculate inner product of row i in A with row j in B meaning we are using different combinations of rows and columns to calculate inner products for each value [i][j] whether we do one or the other first.



In [12]:
print(A * C)

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]


Different from dot product as the dot product calculates each value as the `i`th row from A's inner product with the `j`th column from B whereas the elementwise multiplication (`*`) calculates value `(i, j)` simply as `A[i][j] * B[i][j]`.

In [21]:
np.dot(A, np.linalg.inv(A))

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.55431223e-15,  1.00000000e+00, -2.38919995e-14,
         8.34887715e-15],
       [ 1.29526020e-15,  3.40468394e-15,  1.00000000e+00,
        -6.95739762e-15],
       [ 1.11022302e-15,  1.91592773e-14,  1.70657139e-14,
         1.00000000e+00]])

Differs from the identity matrix very very slightly since floating point calculations are flawed in programming.

In [33]:
invD = np.linalg.inv(D)
invE = np.linalg.inv(E)
invDinvE = np.dot(invD, invE)
ED = np.dot(E, D)
DE = np.dot(D, E)
invED = np.linalg.inv(ED)
invDE = np.linalg.inv(DE)

print(invDinvE - invED)
print(invDinvE - invDE)

[[ 6.e-17 -3.e-17  1.e-16]
 [ 0.e+00  1.e-17 -3.e-17]
 [ 0.e+00 -3.e-17  0.e+00]]
[[ 0.  0. -0.]
 [ 0. -0. -0.]
 [ 0.  0.  0.]]


I honestly don't know why the above acts like it does.

In [43]:
print("A", np.linalg.det(A))
print("B", np.linalg.det(B))
print("C", np.linalg.det(C))

print("A inverse", np.linalg.inv(A))
# print("B inverse", np.linalg.inv(B))
print("C inverse", np.linalg.inv(C))

A 1.6534391534393054e-07
B 0.0
C 1.0498026371041239e-07
A inverse [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
C inverse [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]


Error when calculating inverse matrix of `B` as this is not possible.

In [46]:
np.linalg.inv(A).T - np.linalg.inv(A.T)

array([[ 0.e+00, -7.e-14,  3.e-13, -2.e-13],
       [ 7.e-14,  0.e+00, -9.e-13,  7.e-13],
       [-3.e-13,  9.e-13,  0.e+00, -9.e-13],
       [ 2.e-13, -7.e-13,  9.e-13,  0.e+00]])

Floating point issues means it looks to be different but in fact they are the same apart from some small rounding errors.

In [64]:
# a)
a1 = np.array([[2, 3], [1, 1]])
a2 = np.array([-1, 0])
print("A", np.linalg.inv(a1) @ a2)

# b)
b1 = np.array([[1, 0], [0, 1]])
b2 = np.array([5, 7])
print("B", np.linalg.inv(b1) @ b2)

# c)
c1 = np.array([[0, 1], [-2, -3]])
c2 = np.array([-1, 2])
print("C", np.linalg.inv(c1) @ c2)

# d)
d1 = np.array([[1, -3, 3], [1, -5, 3], [4, -6, 6]])
d2 = np.array([0.5, 0.5, 1])
print("D", np.linalg.inv(d1) @ d2)

# e)
e1 = np.array([[2, 3, 4], [1, 1, 4], [2, 5, 4]])
e2 = np.array([2, -2, 3])
print("E", np.linalg.inv(e1) @ e2)

# f)
f1 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
f2 = np.array([2, -2, 3])
if np.linalg.det(f1) == 0:
    print("F no solutions")
else:
    print("F", np.linalg.inv(f1) @ f2)
# Fails since there is no solution (determinant is 0)


A [ 1. -1.]
B [5. 7.]
C [ 0. -1.]
D [ 0.e+00 -3.e-17  2.e-01]
E [ 3.  0. -1.]
F no solutions
